### ISSUE TITLE
Add Expanded Support for Location

### ISSUE THREAD

**Issue by kornha** [kornha/parliament#15]
We currently have location expressed like this;

geoHash
"gcpuvpgh6w"
-------------------------
geoPoint
[51.5033° N, 0.1276° W]

findStories will *sometimes* output a location. 

Here's what we want to do

1-Include in the output a 2 letter country code, eg., CA for Canada.
--Find where location is generated
--Generate a Country code in addition to above
--Save to database
--Edit location.dart and location.g.dart to include these changes in the front json
---location.g.dart is generated, and can be made by running `dart run build_runner build` in the terminal after editing location.dart

Level of effort: 3

**Comment by Georgeackall** [comment]
I am working on it!

**Comment by Georgeackall** [comment]
https://github.com/Georgeackall/parliament_Final-Project/pull/1

**Comment by Georgeackall** [comment]
https://github.com/Georgeackall/parliament_Final-Project/pull/2

**Comment by Georgeackall** [comment]
I created two Pull request one for the post_ai.js and the second for utils.js

**Comment by Georgeackall** [comment]
https://github.com/kornha/parliament/pull/17

**Comment by Georgeackall** [comment]
https://github.com/kornha/parliament/pull/18
